// Command genaot emits the AOT glue for a goccy/wasm2go-transpiled PGlite
// package: the AOTModule shim (NewAOT + the emscripten.AOTModule methods) and
// the env host adapter (implements base.EnvImports). It reads the generated
// package's base.go to enumerate the EnvImports methods and writes
// aot_generated.go into the package directory.
//
// It is run by `go generate -tags aot` after wasm2go; see docs/wasm2go-migration.md.
//
// Usage:
//
//	genaot -dir internal/pgwasm -pkg pgwasm \
//	    -baseimport github.com/moriyoshi/pglite-go/internal/pgwasm/base -kind pglite
package main

import (
	"flag"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const (
	emscriptenImport = "github.com/moriyoshi/pglite-go/emscripten"
	vfsImport        = "github.com/moriyoshi/pglite-go/vfs"
)

// exportEntry describes how a wasm export name maps to a generated top-package
// function, for the Call dispatch. argc counts i32 args after the *Module; ret
// is true if the function returns an i32.
type exportEntry struct {
	goFunc string
	argc   int
	ret    bool
}

// pgliteExports maps the roots pglite-go calls (see wasmpass.DefaultConfig).
var pgliteExports = map[string]exportEntry{
	"__wasm_call_ctors":                    {"WasmCallCtors", 0, false},
	"__wasm_apply_data_relocs":             {"WasmApplyDataRelocs", 0, false},
	"__main_argc_argv":                     {"MainArgcArgv", 2, true},
	"pgl_startPGlite":                      {"PglStartPGlite", 0, false},
	"pgl_pq_flush":                         {"PglPqFlush", 0, false},
	"pgl_getMyProcPort":                    {"PglGetMyProcPort", 0, true},
	"pgl_setPGliteActive":                  {"PglSetPGliteActive", 1, true},
	"pgl_set_rw_cbs":                       {"PglSetRwCbs", 2, false},
	"pgl_set_system_fn":                    {"PglSetSystemFn", 1, false},
	"pgl_set_popen_fn":                     {"PglSetPopenFn", 1, false},
	"pgl_set_pclose_fn":                    {"PglSetPcloseFn", 1, false},
	"pq_buffer_remaining_data":             {"PqBufferRemainingData", 0, true},
	"ProcessStartupPacket":                 {"ProcessStartupPacket", 3, true},
	"PostgresMainLoopOnce":                 {"PostgresMainLoopOnce", 0, false},
	"PostgresMainLongJmp":                  {"PostgresMainLongJmp", 0, false},
	"PostgresSendReadyForQueryIfNecessary": {"PostgresSendReadyForQueryIfNecessary", 0, false},
}

type method struct {
	name   string
	params []param // excludes the leading m *Module
	ret    string  // "" if void
}
type param struct{ name, typ string }

var methodRe = regexp.MustCompile(`^\s*(\w+)\((.*?)\)\s*(\S+)?\s*$`)

func parseEnvImports(baseGo string) []method {
	return parseInterface(baseGo, "EnvImports")
}

func parseInterface(baseGo, iface string) []method {
	src, err := os.ReadFile(baseGo)
	must(err)
	s := string(src)
	i := strings.Index(s, "type "+iface+" interface {")
	if i < 0 {
		fatal(iface + " interface not found in " + baseGo)
	}
	body := s[i:]
	body = body[strings.Index(body, "{")+1:]
	body = body[:strings.Index(body, "\n}")]
	var out []method
	for _, line := range strings.Split(body, "\n") {
		line = strings.TrimSpace(line)
		if line == "" || !strings.Contains(line, "(") {
			continue
		}
		mm := methodRe.FindStringSubmatch(line)
		if mm == nil {
			continue
		}
		var ps []param
		for _, p := range splitParams(mm[2]) {
			f := strings.Fields(p)
			ps = append(ps, param{f[0], strings.Join(f[1:], " ")})
		}
		// drop the leading receiver-ish "m *Module"
		if len(ps) > 0 {
			ps = ps[1:]
		}
		out = append(out, method{mm[1], ps, mm[3]})
	}
	return out
}

func splitParams(s string) []string {
	s = strings.TrimSpace(s)
	if s == "" {
		return nil
	}
	return strings.Split(s, ",")
}

func baseType(t string) string { return strings.ReplaceAll(t, "*Module", "*base.Module") }

func main() {
	dir := flag.String("dir", "", "generated top-package directory")
	pkg := flag.String("pkg", "", "top package name")
	baseImport := flag.String("baseimport", "", "import path of the base subpackage")
	kind := flag.String("kind", "pglite", "pglite|initdb")
	flag.Parse()
	if *dir == "" || *pkg == "" || *baseImport == "" {
		flag.Usage()
		os.Exit(2)
	}
	baseGo := filepath.Join(*dir, "base", "base.go")
	methods := parseEnvImports(baseGo)
	// The same host struct also implements the WASI interface, so file I/O routes
	// through the VFS-backed handlers instead of wasm2go's host-backed DefaultWASI.
	methods = append(methods, parseInterface(baseGo, "Wasi_snapshot_preview1Imports")...)

	var b strings.Builder
	p := func(f string, a ...any) { fmt.Fprintf(&b, f, a...); b.WriteByte('\n') }

	p("// Code generated by internal/genaot; DO NOT EDIT.")
	p("//go:build aot")
	p("")
	p("package %s", *pkg)
	p("")
	p("import (")
	p("\t%q", "context")
	p("\tbase %q", *baseImport)
	p("\temcompat %q", emscriptenImport)
	p("\t%q", vfsImport)
	p("\tapi %q", "github.com/tetratelabs/wazero/api")
	p(")")
	p("")

	// env host adapter
	p("// host implements base.EnvImports + base.Wasi_snapshot_preview1Imports. invoke_* trampolines do the indirect")
	p("// call through the exported table; _emscripten_throw_longjmp is the no-op")
	p("// cooperative-unwind driver; the syscalls/runtime funcs route through the")
	p("// shared emscripten handlers via disp.Invoke + the api.Module adapter.")
	p("type host struct {")
	p("\tfs      *vfs.FS")
	p("\tstdin   []byte")
	p("\tcapture *[]byte")
	p("\tdisp    *emcompat.AOTDispatch")
	p("}")
	p("")
	p("// aotHostModule wraps m as an api.Module for the shared handlers.")
	p("func (h *host) mod(m *base.Module) api.Module {")
	p("\treturn emcompat.NewAOTModuleAdapter(func() []byte { return m.Memory }, func(n string, a []uint64) uint64 { return aotCall(m, n, a) })")
	p("}")
	p("")
	for _, m := range methods {
		emitMethod(p, m)
	}

	// AOTModule shim
	p("// aotModule adapts the transpiled *base.Module to emcompat.AOTModule.")
	p("type aotModule struct{ m *base.Module }")
	p("")
	p("func (a *aotModule) Memory() []byte  { return a.m.Memory }")
	p("func (a *aotModule) ApplyDataRelocs() { WasmApplyDataRelocs(a.m) }")
	p("func (a *aotModule) CallCtors()       { WasmCallCtors(a.m) }")
	p("func (a *aotModule) SP() int32        { return a.m.G1 }") // __stack_pointer
	p("func (a *aotModule) SetSP(v int32)    { a.m.G1 = v }")
	p("")
	emitCall(p, *kind)
	emitRegisterRW(p)
	emitRegisterInitdb(p)

	// constructor
	p("// NewAOT wires the env/WASI host adapter, instantiates the transpiled")
	p("// module (New uses the built-in DefaultWASI), and returns it as an")
	p("// emcompat.AOTModule for A2GRuntime to drive.")
	p("func NewAOT(fs *vfs.FS, stdin []byte, capture *[]byte) emcompat.AOTModule {")
	p("\th := &host{fs: fs, stdin: stdin, capture: capture, disp: emcompat.NewAOTDispatch(fs, stdin, capture)}")
	p("\t// Reserve headroom so emscripten_resize_heap can grow the heap by")
	p("\t// reslicing (no realloc → cached m.M stays valid).")
	p("\treturn &aotModule{m: NewWithWASIReserve(h, h, 768<<20)}")
	p("}")
	p("")
	p("func aotI32(v uint64) int32 { return int32(uint32(v)) }")
	p("")
	p("var _ = context.Background")

	out := filepath.Join(*dir, "aot_generated.go")
	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		// still write unformatted for debugging
		_ = os.WriteFile(out, []byte(b.String()), 0o644)
		fatal(fmt.Sprintf("format: %v (wrote unformatted to %s)", err, out))
	}
	must(os.WriteFile(out, formatted, 0o644))
	fmt.Fprintf(os.Stderr, "genaot: wrote %s (%d EnvImports methods)\n", out, len(methods))
}

func emitMethod(p func(string, ...any), m method) {
	// build signature
	var sig []string
	for _, pr := range m.params {
		sig = append(sig, pr.name+" "+baseType(pr.typ))
	}
	params := "m *base.Module"
	if len(sig) > 0 {
		params += ", " + strings.Join(sig, ", ")
	}
	retClause := ""
	if m.ret != "" {
		retClause = " " + m.ret
	}
	p("func (h *host) %s(%s)%s {", m.name, params, retClause)
	switch {
	case m.name == "X_emscripten_throw_longjmp":
		p("\t// cooperative unwind: __THREW__ already set; just return")
	case m.name == "Emscripten_resize_heap":
		// Grow by reslicing within the pre-reserved cap so the backing array —
		// and every caller's cached m.M base pointer — stays valid (a realloc
		// mid-execution would corrupt them).
		p("\tnewLen := uint64(uint32(%s))", m.params[0].name)
		p("\tif newLen <= m.MemSize.Load() {")
		p("\t\treturn 1")
		p("\t}")
		p("\tif newLen > uint64(cap(m.Memory)) {")
		p("\t\treturn 0")
		p("\t}")
		p("\tm.Memory = m.Memory[:newLen]")
		p("\tm.MemSize.Store(newLen)")
		p("\treturn 1")
	case strings.HasPrefix(m.name, "Invoke_"):
		// params[0] = table index; rest = call args
		idx := m.params[0].name
		callArgs := m.params[1:]
		var argTypes, argVals []string
		for _, a := range callArgs {
			argTypes = append(argTypes, baseType(a.typ))
			argVals = append(argVals, a.name)
		}
		fnsig := "func(*base.Module"
		if len(argTypes) > 0 {
			fnsig += ", " + strings.Join(argTypes, ", ")
		}
		fnsig += ")"
		if m.ret != "" {
			fnsig += " " + m.ret
		}
		call := fmt.Sprintf("m.T0[%s].(%s)(m%s)", idx, fnsig, prefixComma(argVals))
		if m.ret != "" {
			p("\treturn %s", call)
		} else {
			p("\t%s", call)
		}
	default:
		// route through the shared host handler via the api.Module adapter
		np := len(m.params)
		nr := 0
		if m.ret != "" {
			nr = 1
		}
		stackSize := np
		if nr > stackSize {
			stackSize = nr
		}
		p("\tstack := make([]uint64, %d)", stackSize)
		var vts []string
		for i, pr := range m.params {
			p("\tstack[%d] = %s", i, encFor(pr.typ, pr.name))
			vts = append(vts, vtByte(pr.typ))
		}
		resVT := ""
		if m.ret != "" {
			resVT = vtByte(m.ret)
		}
		p("\th.disp.Invoke(%q, h.mod(m), stack, []byte{%s}, []byte{%s})", origName(m.name), strings.Join(vts, ", "), resVT)
		if m.ret != "" {
			p("\treturn %s", decFor(m.ret))
		}
	}
	p("}")
	p("")
}

func prefixComma(vals []string) string {
	if len(vals) == 0 {
		return ""
	}
	return ", " + strings.Join(vals, ", ")
}

func origName(m string) string {
	if strings.HasPrefix(m, "X_") {
		return m[1:] // X__syscall_openat -> __syscall_openat ; X_abort_js -> _abort_js
	}
	return strings.ToLower(m[:1]) + m[1:] // Emscripten_resize_heap -> emscripten_resize_heap
}
func encFor(typ, name string) string {
	switch typ {
	case "int64":
		return "api.EncodeI64(" + name + ")"
	case "float64":
		return "api.EncodeF64(" + name + ")"
	case "float32":
		return "api.EncodeF32(" + name + ")"
	}
	return "api.EncodeI32(" + name + ")"
}
func decFor(typ string) string {
	switch typ {
	case "int64":
		return "api.DecodeI64(stack[0])"
	case "float64":
		return "api.DecodeF64(stack[0])"
	case "float32":
		return "api.DecodeF32(stack[0])"
	}
	return "api.DecodeI32(stack[0])"
}
func vtByte(typ string) string {
	switch typ {
	case "int64":
		return "0x7e"
	case "float64":
		return "0x7c"
	case "float32":
		return "0x7d"
	}
	return "0x7f"
}

func emitCall(p func(string, ...any), kind string) {
	table := pgliteExports
	if kind == "initdb" {
		table = map[string]exportEntry{} // TODO(aot): initdb export roots
	}
	p("func (a *aotModule) Call(name string, args []uint64) uint64 { return aotCall(a.m, name, args) }")
	p("")
	p("// aotCall dispatches an exported function by name (wasm value lanes).")
	p("func aotCall(m *base.Module, name string, args []uint64) uint64 {")
	p("\tswitch name {")
	for name, e := range table {
		var callArgs []string
		for i := 0; i < e.argc; i++ {
			callArgs = append(callArgs, fmt.Sprintf("aotI32(args[%d])", i))
		}
		invoke := fmt.Sprintf("%s(m%s)", e.goFunc, prefixComma(callArgs))
		p("\tcase %q:", name)
		if e.ret {
			p("\t\treturn uint64(uint32(%s))", invoke)
		} else {
			p("\t\t%s", invoke)
			p("\t\treturn 0")
		}
	}
	p("\tdefault:")
	p("\t\tpanic(\"aot: unknown export \" + name)")
	p("\t}")
	p("}")
	p("")
}

func emitRegisterRW(p func(string, ...any)) {
	p("// RegisterRW appends the socket read/write callbacks to the table and")
	p("// returns their base index (base+0=read, base+1=write). Signatures match")
	p("// the wazero backend: (ptr i32, len i32) -> i32.")
	p("func (a *aotModule) RegisterRW(read func(dst []byte) int, write func(src []byte)) uint32 {")
	p("\tidx := uint32(len(a.m.T0))")
	p("\treadFn := func(m *base.Module, ptr, max int32) int32 {")
	p("\t\ttmp := make([]byte, max)")
	p("\t\tn := read(tmp)")
	p("\t\tif n > 0 {")
	p("\t\t\tcopy(m.Memory[ptr:ptr+int32(n)], tmp[:n])")
	p("\t\t}")
	p("\t\treturn int32(n)")
	p("\t}")
	p("\twriteFn := func(m *base.Module, ptr, length int32) int32 {")
	p("\t\twrite(m.Memory[ptr : ptr+length])")
	p("\t\treturn length")
	p("\t}")
	p("\ta.m.T0 = append(a.m.T0, readFn, writeFn)")
	p("\treturn idx")
	p("}")
	p("")
}

func emitRegisterInitdb(p func(string, ...any)) {
	p("// RegisterInitdb appends the system/popen/pclose callbacks and returns the")
	p("// base index. TODO(aot): match the exact table-entry signatures and FILE*")
	p("// handling from emscripten/systemcb.go; not exercised until the initdb path.")
	p("func (a *aotModule) RegisterInitdb(cb *emcompat.InitdbCallbacks) uint32 {")
	p("\tidx := uint32(len(a.m.T0))")
	p("\tsystemFn := func(m *base.Module, cmd int32) int32 {")
	p("\t\treturn cb.OnSystem(context.Background(), aotCStr(m.Memory, cmd))")
	p("\t}")
	p("\tpopenFn := func(m *base.Module, cmd, mode int32) int32 {")
	p("\t\treturn cb.OnPopen(context.Background(), aotCStr(m.Memory, cmd), aotCStr(m.Memory, mode))")
	p("\t}")
	p("\tpcloseFn := func(m *base.Module, stream int32) int32 {")
	p("\t\treturn cb.OnPclose(context.Background(), stream)")
	p("\t}")
	p("\ta.m.T0 = append(a.m.T0, systemFn, popenFn, pcloseFn)")
	p("\treturn idx")
	p("}")
	p("")
	p("func aotCStr(mem []byte, ptr int32) string {")
	p("\tif ptr == 0 {")
	p("\t\treturn \"\"")
	p("\t}")
	p("\tend := int(ptr)")
	p("\tfor end < len(mem) && mem[end] != 0 {")
	p("\t\tend++")
	p("\t}")
	p("\treturn string(mem[ptr:end])")
	p("}")
	p("")
}

func must(err error) {
	if err != nil {
		fatal(err.Error())
	}
}
func fatal(s string) {
	fmt.Fprintln(os.Stderr, "genaot:", s)
	os.Exit(1)
}
